services:
  backend:
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  frontend:
    container_name: ${FRONTEND_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend

  mongo:
    container_name: mongo
    image: mongo:8.0
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
    - mongo_data:/data/db


volumes:
  mongo_data:
