# /backend/Dockerfile.backend
FROM node:18-alpine

# Use /app as the working directory
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Expose the backend port.
EXPOSE 5000


CMD ["npm", "start"]

